name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: g++ ./Tests/test1.cpp -o ./test1
        command: "./test1"
        input: '957.87'
        expected-output: 9 $100 bill(s), 1 $50 bill(s), 1 $5 bill(s), 2 $1 bill(s),
          3 quarter(s), 1 dime(s), 2 penny(ies),
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: g++ ./Tests/test2.cpp -o ./test2
        command: "./test2"
        input: '12.87'
        expected-output: 1 $10 bill(s), 2 $1 bill(s), 3 quarter(s), 1 dime(s), 2 penny(ies),
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: g++ ./Tests/test3.cpp -o ./test3
        command: "./test3"
        input: '2467.67'
        expected-output: 24 $100 bill(s), 1 $50 bill(s), 1 $10 bill(s), 1 $5 bill(s),
          2 $1 bill(s), 2 quarter(s), 1 dime(s), 1 nickel(s), 2 penny(ies),
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
      with:
        runners: test-1,test-2,test-3
